name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Call Build Workflow
        uses: ./.github/workflows/build.yml
        with:
          python-version: '3.10'
          environment: 'production'

      - name: Deploy application
        run: |
          echo "Deploying application to ${{ inputs.environment }} environment"
          # Add deployment commands here