name: Nightly Build

on:
  schedule:
    - cron: "0 2 * * *" # 2 AM UTC daily

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run tests
      run: pytest