name: Notifications

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
    - name: Send Slack notification
      uses: slackapi/slack-github-action@v1.24.0
      with:
        slack-message: "Pipeline status: ${{ job.status }}"
        slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}